# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bodyreader/bodyList.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import bodyreader.msg

class bodyList(genpy.Message):
  _md5sum = "a1b1dea345dbea1f84926cdcaf9c5b80"
  _type = "bodyreader/bodyList"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 count
body[6] bodies
================================================================================
MSG: bodyreader/body
int16 bodyid
vector3f centerOfMass
joint[19] joints
================================================================================
MSG: bodyreader/vector3f
float32 x
float32 y
float32 z
================================================================================
MSG: bodyreader/joint
int8 type
vector2f depthPosition
vector3f worldPosition
================================================================================
MSG: bodyreader/vector2f
float32 x
float32 y"""
  __slots__ = ['count','bodies']
  _slot_types = ['int8','bodyreader/body[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       count,bodies

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bodyList, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.count is None:
        self.count = 0
      if self.bodies is None:
        self.bodies = [bodyreader.msg.body() for _ in range(6)]
    else:
      self.count = 0
      self.bodies = [bodyreader.msg.body() for _ in range(6)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.count
      buff.write(_get_struct_b().pack(_x))
      if len(self.bodies) != 6:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (6, len(self.bodies), 'self.bodies')))
      for val1 in self.bodies:
        _x = val1.bodyid
        buff.write(_get_struct_h().pack(_x))
        _v1 = val1.centerOfMass
        _x = _v1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        if len(val1.joints) != 19:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (19, len(val1.joints), 'val1.joints')))
        for val2 in val1.joints:
          _x = val2.type
          buff.write(_get_struct_b().pack(_x))
          _v2 = val2.depthPosition
          _x = _v2
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
          _v3 = val2.worldPosition
          _x = _v3
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bodies is None:
        self.bodies = None
      end = 0
      start = end
      end += 1
      (self.count,) = _get_struct_b().unpack(str[start:end])
      self.bodies = []
      for i in range(0, 6):
        val1 = bodyreader.msg.body()
        start = end
        end += 2
        (val1.bodyid,) = _get_struct_h().unpack(str[start:end])
        _v4 = val1.centerOfMass
        _x = _v4
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        val1.joints = []
        for i in range(0, 19):
          val2 = bodyreader.msg.joint()
          start = end
          end += 1
          (val2.type,) = _get_struct_b().unpack(str[start:end])
          _v5 = val2.depthPosition
          _x = _v5
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          _v6 = val2.worldPosition
          _x = _v6
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.joints.append(val2)
        self.bodies.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.count
      buff.write(_get_struct_b().pack(_x))
      if len(self.bodies) != 6:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (6, len(self.bodies), 'self.bodies')))
      for val1 in self.bodies:
        _x = val1.bodyid
        buff.write(_get_struct_h().pack(_x))
        _v7 = val1.centerOfMass
        _x = _v7
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        if len(val1.joints) != 19:
          self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (19, len(val1.joints), 'val1.joints')))
        for val2 in val1.joints:
          _x = val2.type
          buff.write(_get_struct_b().pack(_x))
          _v8 = val2.depthPosition
          _x = _v8
          buff.write(_get_struct_2f().pack(_x.x, _x.y))
          _v9 = val2.worldPosition
          _x = _v9
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bodies is None:
        self.bodies = None
      end = 0
      start = end
      end += 1
      (self.count,) = _get_struct_b().unpack(str[start:end])
      self.bodies = []
      for i in range(0, 6):
        val1 = bodyreader.msg.body()
        start = end
        end += 2
        (val1.bodyid,) = _get_struct_h().unpack(str[start:end])
        _v10 = val1.centerOfMass
        _x = _v10
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        val1.joints = []
        for i in range(0, 19):
          val2 = bodyreader.msg.joint()
          start = end
          end += 1
          (val2.type,) = _get_struct_b().unpack(str[start:end])
          _v11 = val2.depthPosition
          _x = _v11
          start = end
          end += 8
          (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
          _v12 = val2.worldPosition
          _x = _v12
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.joints.append(val2)
        self.bodies.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
