// Generated by gencpp from file bodyreader/bodyList.msg
// DO NOT EDIT!


#ifndef BODYREADER_MESSAGE_BODYLIST_H
#define BODYREADER_MESSAGE_BODYLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bodyreader/body.h>

namespace bodyreader
{
template <class ContainerAllocator>
struct bodyList_
{
  typedef bodyList_<ContainerAllocator> Type;

  bodyList_()
    : count(0)
    , bodies()  {
    }
  bodyList_(const ContainerAllocator& _alloc)
    : count(0)
    , bodies()  {
  (void)_alloc;
      bodies.assign( ::bodyreader::body_<ContainerAllocator> (_alloc));
  }



   typedef int8_t _count_type;
  _count_type count;

   typedef boost::array< ::bodyreader::body_<ContainerAllocator> , 6>  _bodies_type;
  _bodies_type bodies;





  typedef boost::shared_ptr< ::bodyreader::bodyList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bodyreader::bodyList_<ContainerAllocator> const> ConstPtr;

}; // struct bodyList_

typedef ::bodyreader::bodyList_<std::allocator<void> > bodyList;

typedef boost::shared_ptr< ::bodyreader::bodyList > bodyListPtr;
typedef boost::shared_ptr< ::bodyreader::bodyList const> bodyListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bodyreader::bodyList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bodyreader::bodyList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bodyreader::bodyList_<ContainerAllocator1> & lhs, const ::bodyreader::bodyList_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count &&
    lhs.bodies == rhs.bodies;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bodyreader::bodyList_<ContainerAllocator1> & lhs, const ::bodyreader::bodyList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bodyreader

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bodyreader::bodyList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bodyreader::bodyList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bodyreader::bodyList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bodyreader::bodyList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bodyreader::bodyList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bodyreader::bodyList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bodyreader::bodyList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1b1dea345dbea1f84926cdcaf9c5b80";
  }

  static const char* value(const ::bodyreader::bodyList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1b1dea345dbea1fULL;
  static const uint64_t static_value2 = 0x84926cdcaf9c5b80ULL;
};

template<class ContainerAllocator>
struct DataType< ::bodyreader::bodyList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bodyreader/bodyList";
  }

  static const char* value(const ::bodyreader::bodyList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bodyreader::bodyList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 count\n"
"body[6] bodies\n"
"================================================================================\n"
"MSG: bodyreader/body\n"
"int16 bodyid\n"
"vector3f centerOfMass\n"
"joint[19] joints\n"
"================================================================================\n"
"MSG: bodyreader/vector3f\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: bodyreader/joint\n"
"int8 type\n"
"vector2f depthPosition\n"
"vector3f worldPosition\n"
"================================================================================\n"
"MSG: bodyreader/vector2f\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::bodyreader::bodyList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bodyreader::bodyList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
      stream.next(m.bodies);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bodyList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bodyreader::bodyList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bodyreader::bodyList_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int8_t>::stream(s, indent + "  ", v.count);
    s << indent << "bodies[]" << std::endl;
    for (size_t i = 0; i < v.bodies.size(); ++i)
    {
      s << indent << "  bodies[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::bodyreader::body_<ContainerAllocator> >::stream(s, indent + "    ", v.bodies[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BODYREADER_MESSAGE_BODYLIST_H
