(cl:in-package bodyreader-msg)
(cl:export '(BODYID-VAL
          BODYID
          CENTEROFMASS_X-VAL
          CENTEROFMASS_X
          CENTEROFMASS_Y-VAL
          CENTEROFMASS_Y
          CENTEROFMASS_Z-VAL
          CENTEROFMASS_Z
          LEFT_ARM_OUT-VAL
          LEFT_ARM_OUT
          RIGHT_ARM_OUT-VAL
          RIGHT_ARM_OUT
          LEFT_HAND_RAISED-VAL
          LEFT_HAND_RAISED
          RIGHT_HAND_RAISED-VAL
          RIGHT_HAND_RAISED
          AKIMIBO-VAL
          AKIMIBO
          LEFT_FOOT_UP-VAL
          LEFT_FOOT_UP
          RIGHT_FOOT_UP-VAL
          RIGHT_FOOT_UP
          FALL-VAL
          FALL
          TIPS-VAL
          TIPS
          LOCK_STATUS-VAL
          LOCK_STATUS
))